version: "3.9"
services:
  postgres-webchat:
    container_name: postgres-webchat
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - main
    restart: unless-stopped

  server-webchat:
    container_name: server-webchat
    restart: always
    depends_on: 
      - postgres-webchat
    build: ./server
    ports:
      - "${PORT}:8080"
    env_file: .env
    environment:
      - SSL=${SSL}
      - HASH_SECRET=${HASH_SECRET}
    #volumes:
    #  - ./brbot-web/server/static/assets:/static/assets
    networks:
      - main

  nginx-webchat:
    build: ./client
    #image: nginx:latest
    container_name: nginx-webchat
    restart: unless-stopped
    ports:
      - 443:443
    links:
      - server-webchat:server-webchat
    depends_on:
      - server-webchat
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./security/keys/:/ssl/
      #- ./public/:/usr/share/nginx/html
    networks:
      - main
          
networks:
  main:
    driver: bridge

volumes:
  db:
    driver: local