version: "3.9"
services:
  postgres-webchat:
    container_name: postgres-webchat
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/data/postgres
    volumes: 
#      - ./constructor.sql:/docker-entrypoint-initdb.d/constructor.sql
      - db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      main:
        aliases:
          - postgres
    restart: unless-stopped

  nginx-webchat:
    #build: ./brbot-web/react
    image: nginx:latest
    container_name: nginx-webchat
    restart: unless-stopped
    ports:
      - 443:443
    #links:
    #  - brbotweb:brbotweb
    #  - brbot:brbot
    #  - brbotsum:brbotsum
    #depends_on:
    #  - brbot
    #  - brbotweb
    #  - brbotsum
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./security/keys/:/ssl/
      - ./public/:/usr/share/nginx/html
    networks:
      main:
        aliases:
          - nginx
          
networks:
  main:
    driver: bridge

volumes:
  db:
    driver: local