name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASS }}
        
    - name: Build and push Docker images from Client
      uses: docker/build-push-action@v4.1.1
      with:
        context: ./client
        push: true
        tags: |
          luisgzanetti/web-chat-client:v1
          luisgzanetti/web-chat-client:latest
          
    - name: Build and push Docker images from Server
      uses: docker/build-push-action@v4.1.1
      with:
        context: ./server
        push: true
        tags: |
          luisgzanetti/web-chat-server:v1
          luisgzanetti/web-chat-server:latest
          
          
